#!/bin/bash

for i in \
  .zshrc-peco \
  .bashrc_peco \
  .tigrc \
; do
  if [ ! -s $HOME/$i ]; then
    ln -sf $PWD/$i $HOME/$i
  fi
done

if [ ! -s $HOME/.config/git/ignore ]; then
  ln -sf $PWD/.config/git/ignore $HOME/.config/git/ignore
fi